# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: colin bayer - Web Developer in Portland, OR
email: ccbayer@gmail.com
description: ""
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://colinbayer.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ccbayer
github_username:  ccbayer
linkedin: https://www.linkedin.com/in/ccbayer

# defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      post_thumbnail: "/images/plaid-swatch.svg"

# collections
collections:
  sandbox:
    output: true
    permalink: :collection/:title
  projects:
    output: true
    permalink: :collection/:title

# permalink settings
permalink: /blog/:year/:month/:day/:title


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives

# archive settings
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

sass:
  sass_dir: _sass
  style: :compressed
  load_paths:
    - _sass
    - node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
